### ISSUE TITLE
Swoosh not compatible with NodeJS 18 and being deprecated

### ISSUE THREAD

**Issue by rodrigolj** [craftzdog/craftzdog-uses#6]
Astro's image integration uses swoosh by default, which doesn't work with NodeJS 18 (required to run [inkdrop-live-export](https://github.com/inkdropapp/inkdrop-live-export)). Also, it was said to being deprecated soon (https://github.com/GoogleChromeLabs/squoosh/pull/1266#issuecomment-1208149979).

I suggest using the optional installation of sharp, as per the guide on [the Astro documentation](https://docs.astro.build/pt-br/guides/integrations-guide/image/#installing-sharp-optional).

**Comment by craftzdog** [comment]
I guess you are talking about Squoosh.
Is the Astro team aware of it?

**Comment by rodrigolj** [comment]
> I guess you are talking about Squoosh.
> Is the Astro team aware of it?

Yes. They said it won't be fixed by them, because it is an issue upstream. I tried your code with NodeJS 18 and the latest Astro, that's how I found the problem.

**Comment by craftzdog** [comment]
Hmm, node 18 is already in LTS so they should be on it though🤔
Can you tell me the issue URL where they said that?
Also, did using sharp solve it for you?

**Comment by rodrigolj** [comment]
https://github.com/withastro/astro/issues/5051

Using sharp solved it.

**Comment by craftzdog** [comment]
ah, node fetch doesn't support file URIs - makes sense
